# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19BebbCtxie-54ZfrcijFOC1jc4ZYaiN4

# Importing Libs
"""

import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

model=DecisionTreeRegressor(random_state=1)

"""# **Importing the DataSet**"""

df=pd.read_csv('Breast_cancer_data.csv')
df

"""# Selecting Value And Features For the Model"""

X_train,X_test,y_train,y_test=train_test_split(X,y , test_size=5, random_state=1)

X_train

model.fit(X_train,y_train)

X_test

df.columns[2]

inputs=[]

for i in range(5):
  inputs.append(input('Please Enter '+df.columns[i]+" "))

X_predict=model.predict([inputs])
print(X_predict)

xt=pd.read_csv('Breast_cancer_data.csv')
xt.iloc[[47]]